### ISSUE TITLE
 list index out of range [main loop]

### ISSUE THREAD

**Issue by sklbancor** [bancorprotocol/fastlane-bot#101]
2023-08-31 13:54:11,234 [fastlane:ERROR] - Error in main loop: list index out of range
Traceback (most recent call last):
  File "/root/fastlanebot/main.py", line 546, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in call
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/fastlanebot/main.py", line 332, in main
    run(
  File "/root/fastlanebot/main.py", line 522, in run
    forks_to_cleanup = delete_tenderly_forks(forks_to_cleanup, mgr)
  File "/root/fastlanebot/fastlane_bot/events/utils.py", line 1383, in delete_tenderly_forks
    forks_to_keep = [forks_to_cleanup[-1], forks_to_cleanup[-2]]
IndexError: list index out of range

**Comment by sklbancor** [comment]
export TENDERLY_PROJECT=
export TENDERLY_USER=

**Comment by sklbancor** [comment]
branch balancer2
