### ISSUE TITLE
multiple runtime errors in latest main branch

### ISSUE THREAD

**Issue by pblaas** [bancorprotocol/fastlane-bot#213]
Hi, 

While running the current latest version of the bot I noticed the following errors in the bot logs.

- Error in main loop: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
- Error writing pool data to disk: Object of type int64 is not JSON serializable

Log snip:
```
2023-11-17 07:42:49,518 [fastlane:ERROR] - Error in main loop: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2023-11-17 07:43:01,806 [fastlane:INFO] - Fetching events from 18590176 to 18590182... 18590178
2023-11-17 07:43:10,342 [fastlane:INFO] - Found 133 new events, 82 carbon_pol_events
2023-11-17 07:43:10,345 [fastlane:INFO] - Saved events to ./logs/20231116-234820/latest_event_data.json
2023-11-17 07:43:36,780 [fastlane:ERROR] - Error writing pool data to disk: Object of type int64 is not JSON serializable
2023-11-17 07:43:36,797 [fastlane:INFO] - Initializing the bot...
2023-11-17 07:43:36,983 [fastlane:INFO] - State has changed...
2023-11-17 07:43:37,101 [fastlane:INFO] - Removed 0 unmapped uniswap_v2/sushi pools. 7754 uniswap_v2/sushi pools remaining
2023-11-17 07:43:37,102 [fastlane:INFO] - Unmapped uniswap_v2/sushi pools:
2023-11-17 07:43:39,012 [fastlane:INFO] - uniswap_v2: 0
2023-11-17 07:43:39,013 [fastlane:INFO] - sushiswap_v2: 0
2023-11-17 07:43:39,053 [fastlane:INFO] - uniswap_v3: 1056
2023-11-17 07:43:39,054 [fastlane:INFO] - sushiswap_v2: 279
2023-11-17 07:43:39,055 [fastlane:INFO] - uniswap_v2: 2124
2023-11-17 07:43:39,056 [fastlane:INFO] - bancor_v2: 27
2023-11-17 07:43:39,056 [fastlane:INFO] - bancor_v3: 14
2023-11-17 07:43:39,057 [fastlane:INFO] - bancor_pol: 72
2023-11-17 07:43:39,058 [fastlane:INFO] - carbon_v1: 189
2023-11-17 07:43:39,058 [fastlane:INFO] - pancakeswap_v2: 8
2023-11-17 07:43:39,059 [fastlane:INFO] - pancakeswap_v3: 31
2023-11-17 07:43:39,059 [fastlane:INFO] - balancer: 63
2023-11-17 07:43:40,036 [fastlane:INFO] - uniswap_v3_zero_liquidity_pools: 855
2023-11-17 07:43:40,038 [fastlane:INFO] - sushiswap_v2_zero_liquidity_pools: 27
2023-11-17 07:43:40,039 [fastlane:INFO] - uniswap_v2_zero_liquidity_pools: 2189
2023-11-17 07:43:40,039 [fastlane:INFO] - bancor_v2_zero_liquidity_pools: 70
2023-11-17 07:43:40,040 [fastlane:INFO] - bancor_v3_zero_liquidity_pools: 0
2023-11-17 07:43:40,040 [fastlane:INFO] - bancor_pol_zero_liquidity_pools: 10
2023-11-17 07:43:40,041 [fastlane:INFO] - carbon_v1_zero_liquidity_pools: 223
2023-11-17 07:43:40,042 [fastlane:INFO] - pancakeswap_v2_zero_liquidity_pools: 422
2023-11-17 07:43:40,042 [fastlane:INFO] - pancakeswap_v3_zero_liquidity_pools: 95
2023-11-17 07:43:40,043 [fastlane:INFO] - balancer_zero_liquidity_pools: 0
2023-11-17 07:43:40,045 [fastlane:INFO] - Removed 0 unsupported exchanges. 3863 pools remaining
2023-11-17 07:43:40,045 [fastlane:INFO] - Pools remaining per exchange:
2023-11-17 07:43:40,046 [fastlane:INFO] - carbon_v1: 189
2023-11-17 07:43:40,047 [fastlane:INFO] - bancor_v3: 14
2023-11-17 07:43:40,047 [fastlane:INFO] - bancor_v2: 27
2023-11-17 07:43:40,048 [fastlane:INFO] - bancor_pol: 72
2023-11-17 07:43:40,049 [fastlane:INFO] - uniswap_v3: 1056
2023-11-17 07:43:40,049 [fastlane:INFO] - uniswap_v2: 2124
2023-11-17 07:43:40,050 [fastlane:INFO] - sushiswap_v2: 279
2023-11-17 07:43:40,051 [fastlane:INFO] - balancer: 63
2023-11-17 07:43:40,051 [fastlane:INFO] - pancakeswap_v2: 8
2023-11-17 07:43:40,052 [fastlane:INFO] - pancakeswap_v3: 31
2023-11-17 07:43:40,226 [fastlane:ERROR] - Error in main loop: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2023-11-17 07:43:52,503 [fastlane:INFO] - Fetching events from 18590180 to 18590187... 18590182
2023-11-17 07:44:01,567 [fastlane:INFO] - Found 143 new events, 82 carbon_pol_events
2023-11-17 07:44:01,570 [fastlane:INFO] - Saved events to ./logs/20231116-234820/latest_event_data.json
2023-11-17 07:44:30,848 [fastlane:ERROR] - Error writing pool data to disk: Object of type int64 is not JSON serializable
2023-11-17 07:44:30,867 [fastlane:INFO] - Initializing the bot...
2023-11-17 07:44:31,046 [fastlane:INFO] - State has changed...
2023-11-17 07:44:31,201 [fastlane:INFO] - Removed 0 unmapped uniswap_v2/sushi pools. 7754 uniswap_v2/sushi pools remaining
2023-11-17 07:44:31,202 [fastlane:INFO] - Unmapped uniswap_v2/sushi pools:
2023-11-17 07:44:33,067 [fastlane:INFO] - uniswap_v2: 0
2023-11-17 07:44:33,067 [fastlane:INFO] - sushiswap_v2: 0
2023-11-17 07:44:33,089 [fastlane:INFO] - uniswap_v3: 1056
2023-11-17 07:44:33,090 [fastlane:INFO] - sushiswap_v2: 279
2023-11-17 07:44:33,091 [fastlane:INFO] - uniswap_v2: 2125
2023-11-17 07:44:33,091 [fastlane:INFO] - bancor_v2: 27
2023-11-17 07:44:33,092 [fastlane:INFO] - bancor_v3: 14
2023-11-17 07:44:33,093 [fastlane:INFO] - bancor_pol: 72
2023-11-17 07:44:33,093 [fastlane:INFO] - carbon_v1: 189
2023-11-17 07:44:33,094 [fastlane:INFO] - pancakeswap_v2: 8
2023-11-17 07:44:33,095 [fastlane:INFO] - pancakeswap_v3: 31
2023-11-17 07:44:33,095 [fastlane:INFO] - balancer: 63
2023-11-17 07:44:34,110 [fastlane:INFO] - uniswap_v3_zero_liquidity_pools: 855
2023-11-17 07:44:34,112 [fastlane:INFO] - sushiswap_v2_zero_liquidity_pools: 27
2023-11-17 07:44:34,112 [fastlane:INFO] - uniswap_v2_zero_liquidity_pools: 2188
2023-11-17 07:44:34,113 [fastlane:INFO] - bancor_v2_zero_liquidity_pools: 70
2023-11-17 07:44:34,114 [fastlane:INFO] - bancor_v3_zero_liquidity_pools: 0
2023-11-17 07:44:34,114 [fastlane:INFO] - bancor_pol_zero_liquidity_pools: 10
2023-11-17 07:44:34,115 [fastlane:INFO] - carbon_v1_zero_liquidity_pools: 223
2023-11-17 07:44:34,115 [fastlane:INFO] - pancakeswap_v2_zero_liquidity_pools: 422
2023-11-17 07:44:34,116 [fastlane:INFO] - pancakeswap_v3_zero_liquidity_pools: 95
2023-11-17 07:44:34,116 [fastlane:INFO] - balancer_zero_liquidity_pools: 0
2023-11-17 07:44:34,118 [fastlane:INFO] - Removed 0 unsupported exchanges. 3864 pools remaining
2023-11-17 07:44:34,118 [fastlane:INFO] - Pools remaining per exchange:
2023-11-17 07:44:34,119 [fastlane:INFO] - carbon_v1: 189
2023-11-17 07:44:34,120 [fastlane:INFO] - bancor_v3: 14
2023-11-17 07:44:34,121 [fastlane:INFO] - bancor_v2: 27
2023-11-17 07:44:34,122 [fastlane:INFO] - bancor_pol: 72
2023-11-17 07:44:34,123 [fastlane:INFO] - uniswap_v3: 1056
2023-11-17 07:44:34,123 [fastlane:INFO] - uniswap_v2: 2125
2023-11-17 07:44:34,124 [fastlane:INFO] - sushiswap_v2: 279
2023-11-17 07:44:34,125 [fastlane:INFO] - balancer: 63
2023-11-17 07:44:34,125 [fastlane:INFO] - pancakeswap_v2: 8
2023-11-17 07:44:34,126 [fastlane:INFO] - pancakeswap_v3: 31
2023-11-17 07:44:34,299 [fastlane:ERROR] - Error in main loop: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

Regards,
Patrick

**Comment by Lesigh-3100** [comment]
Hey Patrick. Thanks for submitting this. Could you specify all Click Option settings that you are using when running the bot?

**Comment by pblaas** [comment]
here you go:
```
@click.option(
    "--cache_latest_only",
    default=True,
--
@click.option(
    "--backdate_pools",
    default=False,
--
@click.option(
    "--static_pool_data_filename",
    default="static_pool_data",
--
@click.option(
    "--arb_mode",
    default="multi_pairwise_all",
--
@click.option(
    "--flashloan_tokens",
    default=f"WBTC-c599,BNT-FF1C,WETH-6Cc2,USDC-eB48,USDT-1ec7,LINK-86CA",
--
@click.option("--n_jobs", default=-1, help="Number of parallel jobs to run")
@click.option(
    "--exchanges",
    default="carbon_v1,bancor_v3,bancor_v2,bancor_pol,uniswap_v3,uniswap_v2,sushiswap_v2,balancer,pancakeswap_v2,pancakeswap_v3",
--
@click.option(
    "--polling_interval",
    default=12,
--
@click.option(
    "--alchemy_max_block_fetch",
    default=2000,
--
@click.option(
    "--reorg_delay",
    default=2,
--
@click.option(
    "--logging_path",
    default="",
--
@click.option(
    "--loglevel",
    default="INFO",
--
@click.option(
    "--static_pool_data_sample_sz",
    default="max",
--
@click.option(
    "--use_cached_events",
    default=False,
--
@click.option(
    "--run_data_validator",
    default=False,
--
@click.option(
    "--randomizer",
    default=3,
--
@click.option(
    "--limit_bancor3_flashloan_tokens",
    default=True,
--
@click.option(
    "--default_min_profit_gas_token",
    default="0.0001",
--
@click.option(
    "--timeout",
    default=None,
--
@click.option(
    "--target_tokens",
    default=None,
--
@click.option(
    "--replay_from_block",
    default=None,
--
@click.option(
    "--tenderly_fork_id",
    default=None,
--
@click.option(
    "--tenderly_event_exchanges",
    default="pancakeswap_v2,pancakeswap_v3",
--
@click.option(
    "--increment_time",
    default=1,
--
@click.option(
    "--increment_blocks",
    default=1,
--
@click.option(
    "--blockchain",
    default="ethereum",
--
@click.option(
    "--pool_data_update_frequency",
    default=-1,
--
@click.option(
    "--use_specific_exchange_for_target_tokens",
    default=None,
--
@click.option(
    "--prefix_path",
    default="",
```

**Comment by Lesigh-3100** [comment]
Thanks!

Regarding this:

- Error writing pool data to disk: Object of type int64 is not JSON serializable
This is a known issue - it should not affect the bot's performance. 

This issue is more concerning:
Error in main loop: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

I haven't been able to reproduce it. What version of Python are you using?

Would you be able to comment out the try/except in the run function in main.py to get a trace to where the error occurs?

**Comment by pblaas** [comment]
I'm using Python 3.9.18. 
I will see what I can dig up regarding the NoneType issue.

**Comment by pblaas** [comment]
Here is the traceback without the Try Except.

```                  
2023-11-17 12:51:15,086 [fastlane:INFO] - Fetching events from 18591565 to 18591712... 18591565
2023-11-17 12:52:28,899 [fastlane:INFO] - Found 540 new events, 82 carbon_pol_events
2023-11-17 12:52:28,905 [fastlane:INFO] - Saved events to ./logs/20231117-122152/latest_event_data.json
2023-11-17 12:52:39,491 [fastlane:INFO] - Adding new token SAITAMA2.0-32f2 to fastlane_bot/data/blockchain_data/ethereum/tokens.csv
2023-11-17 12:52:41,207 [fastlane:INFO] - Adding new token FUND-fBd5 to fastlane_bot/data/blockchain_data/ethereum/tokens.csv
2023-11-17 12:52:50,590 [fastlane:INFO] - Adding new token DARKO-71D7 to fastlane_bot/data/blockchain_data/ethereum/tokens.csv
2023-11-17 12:53:02,791 [fastlane:INFO] - Adding new token USDP-89E1 to fastlane_bot/data/blockchain_data/ethereum/tokens.csv
2023-11-17 12:53:05,292 [fastlane:INFO] - Adding new token DAWGS-6bf9 to fastlane_bot/data/blockchain_data/ethereum/tokens.csv
2023-11-17 12:53:29,699 [fastlane:INFO] - Adding new token UniBone-F977 to fastlane_bot/data/blockchain_data/ethereum/tokens.csv
2023-11-17 12:53:58,245 [fastlane:INFO] - Initializing the bot...
2023-11-17 12:53:58,423 [fastlane:INFO] - State has changed...
2023-11-17 12:53:58,689 [fastlane:INFO] - Updated token data with 6 new tokens
2023-11-17 12:53:58,727 [fastlane:INFO] - Removed 0 unmapped uniswap_v2/sushi pools. 4903 uniswap_v2/sushi pools remaining
2023-11-17 12:53:58,728 [fastlane:INFO] - Unmapped uniswap_v2/sushi pools:
2023-11-17 12:53:59,363 [fastlane:INFO] - uniswap_v2: 0
2023-11-17 12:53:59,364 [fastlane:INFO] - sushiswap_v2: 0
2023-11-17 12:53:59,373 [fastlane:INFO] - uniswap_v3: 0
2023-11-17 12:53:59,374 [fastlane:INFO] - sushiswap_v2: 186
2023-11-17 12:53:59,374 [fastlane:INFO] - uniswap_v2: 1544
2023-11-17 12:53:59,375 [fastlane:INFO] - bancor_v2: 15
2023-11-17 12:53:59,375 [fastlane:INFO] - bancor_v3: 0
2023-11-17 12:53:59,376 [fastlane:INFO] - bancor_pol: 72
2023-11-17 12:53:59,376 [fastlane:INFO] - carbon_v1: 0
2023-11-17 12:53:59,377 [fastlane:INFO] - pancakeswap_v2: 5
2023-11-17 12:53:59,377 [fastlane:INFO] - pancakeswap_v3: 0
2023-11-17 12:53:59,378 [fastlane:INFO] - balancer: 63
2023-11-17 12:53:59,630 [fastlane:INFO] - uniswap_v3_zero_liquidity_pools: 0
2023-11-17 12:53:59,632 [fastlane:INFO] - sushiswap_v2_zero_liquidity_pools: 41
2023-11-17 12:53:59,633 [fastlane:INFO] - uniswap_v2_zero_liquidity_pools: 2460
2023-11-17 12:53:59,633 [fastlane:INFO] - bancor_v2_zero_liquidity_pools: 82
2023-11-17 12:53:59,634 [fastlane:INFO] - bancor_v3_zero_liquidity_pools: 0
2023-11-17 12:53:59,634 [fastlane:INFO] - bancor_pol_zero_liquidity_pools: 10
2023-11-17 12:53:59,635 [fastlane:INFO] - carbon_v1_zero_liquidity_pools: 0
2023-11-17 12:53:59,635 [fastlane:INFO] - pancakeswap_v2_zero_liquidity_pools: 425
2023-11-17 12:53:59,636 [fastlane:INFO] - pancakeswap_v3_zero_liquidity_pools: 0
2023-11-17 12:53:59,636 [fastlane:INFO] - balancer_zero_liquidity_pools: 0
2023-11-17 12:53:59,637 [fastlane:INFO] - Removed 0 unsupported exchanges. 1885 pools remaining
2023-11-17 12:53:59,637 [fastlane:INFO] - Pools remaining per exchange:
2023-11-17 12:53:59,638 [fastlane:INFO] - bancor_v2: 15
2023-11-17 12:53:59,638 [fastlane:INFO] - bancor_pol: 72
2023-11-17 12:53:59,639 [fastlane:INFO] - uniswap_v2: 1544
2023-11-17 12:53:59,639 [fastlane:INFO] - sushiswap_v2: 186
2023-11-17 12:53:59,639 [fastlane:INFO] - balancer: 63
2023-11-17 12:53:59,640 [fastlane:INFO] - pancakeswap_v2: 5
Traceback (most recent call last):
  File "/home/civo/fastlane/main.py", line 736, in <module>
    main()
  File "/usr/local/pyenv/versions/3.9.18/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/pyenv/versions/3.9.18/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/pyenv/versions/3.9.18/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/pyenv/versions/3.9.18/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/civo/fastlane/main.py", line 450, in main
    run(
  File "/home/civo/fastlane/main.py", line 644, in run
    handle_subsequent_iterations(
  File "/home/civo/fastlane/fastlane_bot/events/utils.py", line 899, in handle_subsequent_iterations
    bot.run(
  File "/home/civo/fastlane/fastlane_bot/bot.py", line 1423, in run
    CCm = self.setup_CCm(CCm)
  File "/home/civo/fastlane/fastlane_bot/bot.py", line 1223, in setup_CCm
    CCm = self.get_curves()
  File "/home/civo/fastlane/fastlane_bot/bot.py", line 188, in get_curves
    ADDRDEC = {t.key: (t.address, int(t.decimals)) for t in tokens}
  File "/home/civo/fastlane/fastlane_bot/bot.py", line 188, in <dictcomp>
    ADDRDEC = {t.key: (t.address, int(t.decimals)) for t in tokens}
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

run command: `python main.py --exchanges=bancor_v2,bancor_pol,uniswap_v2,sushiswap_v2,balancer,pancakeswap_v2`

**Comment by pblaas** [comment]
Having performed multiple changes to the bot setup i am currently not unable to reproduce the problem. 
Even with the settings which previously failed multiple times the errors do not occur anymore.

As this is not reproducible I will close the issue.
