### ISSUE TITLE
Bug in events/pool/carbon_v1 parse_event

### ISSUE THREAD

**Issue by Lesigh-3100** [bancorprotocol/fastlane-bot#419]
## Bug Description
The function `parse_event` calls function `parse_orders`, which returns a Tuple. The code below it checks if a List is returned - which should be Tuple. I will remove this handling because the check us unnecessary.

## Severity (High/Medium/Low)
Medium

## Steps to Reproduce
Run but with Carbon until parse_event is called. See an error that occurred from parsing the event. 

## Expected Behavior
Data should be parsed in the format indicated in the check `if isinstance(order0, list) and isinstance(order1, list)`.

## Actual Behavior
Data is parsed using the wrong code.

## Impact Analysis (to be filled by contributors)
- Automated Tests: Are there existing tests covering this? Do we need new tests?
No
- Risks: Potential areas affected by this bug and its probable fix
No
- Performance: Is this bug affecting performance?
No
- Monitoring: Does this affect any current monitoring? Any new alerts needed?
No
- Logging: Any changes required in logging?
No
- Documentation: Updates needed in documentation?
No

**Comment by mikewcasale** [comment]
I do not believe there is a bug here - parse_orders() returns two lists (ie a tuple) and parse_event() checks if indeed these are lists. Is there some error or behavior which implies this is not working as expected? If not, I disagree that there is a bug.

**Comment by Lesigh-3100** [comment]
> I do not believe there is a bug here - parse_orders() returns two lists (ie a tuple) and parse_event() checks if indeed these are lists. Is there some error or behavior which implies this is not working as expected? If not, I disagree that there is a bug.

You are right - this code works. There is an issue somewhere, however. Below is the stacktrace for where I found this exception. It -might- be related to Bancor POL, but I am not sure. 

```2024-03-12 13:11:01,979 [fastlane:INFO] - [bot._run] Found 7 eligible arb opportunities.
2024-03-12 13:11:01,979 [fastlane:INFO] - [bot.validate_pool_data] Validating pool data...
2024-03-12 13:11:03,704 [fastlane:ERROR] - [bot:run:single] tuple indices must be integers or slices, not str
2024-03-12 13:11:03,705 [fastlane:ERROR] - Error in main loop: Traceback (most recent call last):
  File "C:\Users\Kveen\PycharmProjects\fastlane-bot\main.py", line 448, in run
    handle_subsequent_iterations(
  File "C:\Users\Kveen\PycharmProjects\fastlane-bot\fastlane_bot\events\utils.py", line 1061, in handle_subsequent_iterations
    bot.run(
  File "C:\Users\Kveen\PycharmProjects\fastlane-bot\fastlane_bot\bot.py", line 1510, in run
    self.run_single_mode(
  File "C:\Users\Kveen\PycharmProjects\fastlane-bot\fastlane_bot\bot.py", line 1375, in run_single_mode
    tx_hash = self._run(
              ^^^^^^^^^^
  File "C:\Users\Kveen\PycharmProjects\fastlane-bot\fastlane_bot\bot.py", line 511, in _run
    elif self.validate_pool_data(arb_opp=r):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kveen\PycharmProjects\fastlane-bot\fastlane_bot\bot.py", line 641, in validate_pool_data
    fetched_pool = self.db.mgr.update_from_pool_info(pool_info=pool_info)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kveen\PycharmProjects\fastlane-bot\fastlane_bot\events\managers\manager.py", line 136, in update_from_pool_info
    params = pool.update_from_contract(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kveen\PycharmProjects\fastlane-bot\fastlane_bot\events\pools\carbon_v1.py", line 153, in update_from_contract
    params = self.parse_event(self.state, fake_event, "None")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kveen\PycharmProjects\fastlane-bot\fastlane_bot\events\pools\carbon_v1.py", line 92, in parse_event
    data["y_0"] = order0["y"]
                  ~~~~~~^^^^^
TypeError: tuple indices must be integers or slices, not str```

**Comment by Lesigh-3100** [comment]
> I do not believe there is a bug here - parse_orders() returns two lists (ie a tuple) and parse_event() checks if indeed these are lists. Is there some error or behavior which implies this is not working as expected? If not, I disagree that there is a bug.

Update:
I found the actual bug. 

In `pools\carbon_v1.py`, function `update_from_contract`:

Example return from `contract.caller.strategy`:
```
(3743106036130323098097120681749450326077,
 '0x617d08085F68070F00fE4945c1e57013f7600b12',
 ['0x1F573D6Fb3F13d689FF844B4cE37794d79a7FF1C',
  '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE'],
 [(0, 0, 67529602313984, 1961605126121825),
  (0, 0, 35462792969, 4450510153742)])
```
We manipulate this data to the same format as an event, but order0 & order1 are lists when they should be dicts:
```
fake_event = {
            "args": {
                "id": strategy_call[0],
                "order0": strategy_call[3][0],
                "order1": strategy_call[3][1],
            }
        }
```
Should be:
```
fake_event = {
            "args": {
                "id": strategy[0],
                "order0": {"y": strategy[3][0][0], "z": strategy[3][0][0], "A": strategy[3][0][2], "B": strategy[3][0][3]},
                "order1": {"y": strategy[3][1][0], "z": strategy[3][1][0], "A": strategy[3][1][2], "B": strategy[3][1][3]},
            }
        }
```

Otherwise when parse_event is called, it results in a KeyError.

**Comment by barakman** [comment]
> data["y_0"] = order0["y"]
>                   ~~~~~~^^^^^

Now how would that have anything to do with CarbonPOL (or any other contract for that matter?
This is a purely-offchain error, indicating that either `order0` is not a dictionary, or not a dictionary which maps the key `"y"` to any value.

**Comment by Lesigh-3100** [comment]
> > data["y_0"] = order0["y"]
> > ~~~~~~^^^^^
> 
> Now how would that have anything to do with CarbonPOL (or any other contract for that matter)? This is a purely-offchain error, indicating that either `order0` is not a dictionary, or not a dictionary which maps the key `"y"` to any value.

See my follow-up comment. I believe I have found the actual problem.

**Comment by barakman** [comment]
> We manipulate this data to the same format as an event, but order0 & order1 are lists when they should be dicts:

The source of the problem boils down to exactly [what I've pointed in the other PR](https://github.com/bancorprotocol/fastlane-bot/pull/423#discussion_r1521423798) (which is identical to this one, but you've closed it).

Here it is just in case you can't open that link...

Of course, I don't disagree that the previous code was bad by itself in several different aspects, such as:
- In function `parse_orders`, returning two different types
- In this function, deciding the course of action based on the input type
- In this function, assuming that either both inputs are of type `list` or both inputs are not of type `list`
