### ISSUE TITLE
last_updated_block error when mgr.pool_data is empty

### ISSUE THREAD

**Issue by NIXBNT** [bancorprotocol/fastlane-bot#583]
## Bug Description
Critical bug when there is no data in the mgr.pool_data causes a key error on `last_updated_block`

## Severity (High/Medium/Low)
Critical - no data can be collect in this mode

## Steps to Reproduce
This causes fail on tenderly
```python main.py --blockchain=ethereum --backdate_pools=False --arb_mode=multi_pairwise_all --exchanges=carbon_v1 --flashloan_tokens=0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,0x514910771AF9Ca656af840dff83E8264EcF986CA,0x8E870D67F660D95d5be530380D0eC0bd388289E1 --alchemy_max_block_fetch=1 --default_min_profit_gas_token=0.0001 --read_only=False --loglevel=INFO --randomizer=1 --reorg_delay=0 --polling_interval=0 --rpc_url=https://virtual.mainnet.rpc.tenderly.co/b2b37a88-d450-42af-b63e-91d4ed9a9f82```

adding uniswap_v3 to the exchanges fixes the problem but this is not a realistic solution

## Expected Behavior
Not break when no other exchanges specfied

## Actual Behavior
Breaks when empty mgr.pool_data

## Impact Analysis (to be filled by contributors)
- Automated Tests: Are there existing tests covering this? Do we need new tests?
- Risks: Potential areas affected by this bug and its probable fix
- Performance: Is this bug affecting performance?
- Monitoring: Does this affect any current monitoring? Any new alerts needed?
- Logging: Any changes required in logging?
- Documentation: Updates needed in documentation?

**Comment by barakman** [comment]
Some additional insights:
- This is a long-standing issue which occasionally pops up during execution
- I'm suspecting that the problem starts with the way in which data is generated in the terraformer script
- Specifically, the `if skip_pool: return None` logic, which is applied in several different places in the code

**Comment by barakman** [comment]
```
2024-05-04 19:31:37,798 [fastlane:ERROR] - Error in main loop: Traceback (most recent call last):
  File "/Users/barakmanos/Desktop/Bancor/fastlane-bot/main.py", line 382, in run
    _run_async_update_with_retries(mgr, current_block=current_block)
  File "/Users/barakmanos/Desktop/Bancor/fastlane-bot/main.py", line 561, in _run_async_update_with_retries
    async_update_pools_from_contracts(mgr, current_block)
  File "/Users/barakmanos/Desktop/Bancor/fastlane-bot/fastlane_bot/events/async_event_update_utils.py", line 397, in async_update_pools_from_contracts
    new_pool_data_df = pd.DataFrame(new_pool_data).sort_values(
  File "/Users/barakmanos/Library/Caches/pypoetry/virtualenvs/fastlane-bot-iYYeusmj-py3.9/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/Users/barakmanos/Library/Caches/pypoetry/virtualenvs/fastlane-bot-iYYeusmj-py3.9/lib/python3.9/site-packages/pandas/core/frame.py", line 6912, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "/Users/barakmanos/Library/Caches/pypoetry/virtualenvs/fastlane-bot-iYYeusmj-py3.9/lib/python3.9/site-packages/pandas/core/generic.py", line 1850, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'last_updated_block'
```

**Comment by barakman** [comment]
Handled in PR #612

**Comment by barakman** [comment]
Not solved :(

**Comment by barakman** [comment]
Handled in PR #616

**Comment by barakman** [comment]
Solved in 2 place, but there is 1 more to go :(

**Comment by barakman** [comment]
Handled in PR #627
